/*
 * This file is AUTO GENERATED - DO NOT MODIFY this file. 
 * This file contains the function prototypes of ODK 1500S.
 *
 * File created by ODK_CodeGenerator version 205.100.101.18
 * at Mon August 30 17:02:50 2021 
*/

#if !defined ODK_Functions_H
#define ODK_Functions_H

#include "ODK_Types.h"

#ifdef DLL_EXPORT
  #define EXPORT_API extern "C" __declspec(dllexport)
#else
  #define EXPORT_API extern "C"
#endif

// This is generated by Target 1500S for Simulink
// Model name:                  LQ
// Model version:               1.23
//                
// ODK 1500S version:           V2.5
// Target 1500S version:        V4.0         
// MATLAB version:              9.9 (R2020b) 29-Jul-2020
// Simulink version:            10.2 (R2020b) 29-Jul-2020
// MATLAB Coder version:        5.1 (R2020b) 29-Jul-2020
// Simulink Coder version:      9.4 (R2020b) 29-Jul-2020
// 
// ***Model details***
// Step Size:                   0.01
// Default parameter behaviour: Tunable
// External Mode:               Off
// 
// ***ODK 1500S details***  
// Heap Size:                   32k
// Max Block Size:              1024
// Size of thread stack:        32k
// SyncCallParallelCount:       1(max. number of parallel calls into this ODK application)
// ********************************************************
// 
ODK_RESULT OneStep (
  /*IN*/const ODK_DOUBLE Feedback[5],
  /*IN*/const ODK_DOUBLE& Refthickness,
  /*IN*/const ODK_DOUBLE& Refrollingforce,
  /*OUT*/ODK_DOUBLE& xv,
  /*OUT*/ODK_DOUBLE& fx,
  /*OUT*/InternalModelSignals& internalSignals);
#define _ODK_FUNCTION_ONESTEP  ODK_RESULT OneStep (/*IN*/const ODK_DOUBLE Feedback[5], /*IN*/const ODK_DOUBLE& Refthickness, /*IN*/const ODK_DOUBLE& Refrollingforce, /*OUT*/ODK_DOUBLE& xv, /*OUT*/ODK_DOUBLE& fx, /*OUT*/InternalModelSignals& internalSignals)

// This is generated by Target 1500S for Simulink
// Model name:                  LQ
// Model version:               1.23
//                
// ODK 1500S version:           V2.5
// Target 1500S version:        V4.0         
// MATLAB version:              9.9 (R2020b) 29-Jul-2020
// Simulink version:            10.2 (R2020b) 29-Jul-2020
// MATLAB Coder version:        5.1 (R2020b) 29-Jul-2020
// Simulink Coder version:      9.4 (R2020b) 29-Jul-2020
// 
// ***Model details***
// Step Size:                   0.01
// Default parameter behaviour: Tunable
// External Mode:               Off
// 
// ***ODK 1500S details***  
// Heap Size:                   32k
// Max Block Size:              1024
// Size of thread stack:        32k
// SyncCallParallelCount:       1(max. number of parallel calls into this ODK application)
// ********************************************************
// 
// Call this function to read or write parameters from/to Simulink Model.
// Set write[IN] parameter to TRUE in order to write and set FALSE to read parameters
ODK_RESULT ReadWriteParameters (
  /*IN*/const ODK_BOOL& write,
  /*INOUT*/Params& inOutParams);
#define _ODK_FUNCTION_READWRITEPARAMETERS  ODK_RESULT ReadWriteParameters (/*IN*/const ODK_BOOL& write, /*INOUT*/Params& inOutParams)

#endif